# Generated by Django 3.1.3 on 2021-02-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('deptName', models.CharField(blank=True, max_length=200)),
                ('desc', models.TextField(blank=True, max_length=10000000)),
                ('formurl', models.URLField(blank=True, max_length=100000000000)),
            ],
        ),
    ]
