# Generated by Django 3.1.3 on 2021-02-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210223_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact',
            field=models.IntegerField(blank=True, default='9820050976', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='ongoing',
            field=models.IntegerField(blank=True, default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='event',
            name='ongoingurl',
            field=models.URLField(blank=True, max_length=100000000000),
        ),
    ]
