# Generated by Django 3.1.3 on 2021-02-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210224_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ongoing',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
