# Generated by Django 3.1.5 on 2021-01-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='quote',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='member',
            name='course',
        ),
        migrations.RemoveField(
            model_name='member',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='member',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='member',
            name='year',
        ),
        migrations.AddField(
            model_name='member',
            name='giflink',
            field=models.URLField(blank=True, max_length=1000000),
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
