# Generated by Django 3.1.3 on 2021-02-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210125_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='giflink',
        ),
        migrations.AddField(
            model_name='member',
            name='gifurl',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
