# Generated by Django 3.1.5 on 2021-02-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210203_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gifurl',
            field=models.URLField(blank=True, max_length=100000000000000000000000000000000),
        ),
    ]
